import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';
import {
  ClientCapabilities,
  DidChangeWatchedFilesRegistrationOptions,
  DocumentSelector,
  DynamicFeature,
  FeatureState,
  LanguageClient,
  LanguageClientOptions,
  RegistrationData,
  RegistrationType,
  RevealOutputChannelOn,
  ServerCapabilities,
  ServerOptions,
  State,
  Trace
} from 'vscode-languageclient/node';
import {
  QtProjectManifest,
  getActiveQtBuildProfile,
  getPersistedQtBuildMode,
  getQtInstallationPreference,
  isQtProjectManifestPath,
  readQtProjectManifest,
  resolveQtProjectFiles,
  writeQtProjectManifest
} from '../model/qtProjectManifest';
import { QpmQtInstallation, QpmQtInstallationService } from './qpmQtInstallationService';
import { QpmWorkspaceService } from './qpmWorkspaceService';

export type QpmQmlLanguageServerState = 'disabled' | 'stopped' | 'starting' | 'running' | 'conflict' | 'error';

export interface QpmQmlLanguageReport {
  project: string;
  projectRoot: string;
  state: QpmQmlLanguageServerState;
  executable?: string;
  qtVersion?: string;
  buildDirectories: string[];
  importPaths: string[];
  qmlFiles: number;
  configurationFile: string;
  officialExtensionInstalled: boolean;
  lastError?: string;
}

interface ActiveQmlContext {
  manifestPath: string;
  root: string;
  manifest: QtProjectManifest;
  installation?: QpmQtInstallation;
  executable?: string;
  buildDirectories: string[];
  importPaths: string[];
  workspaceFolder?: vscode.WorkspaceFolder;
}

const GENERATED_MARKER = '; Generated by Qt Project Manager';
const OFFICIAL_QML_EXTENSION_ID = 'TheQtCompany.qt-qml';

export class QpmQmlLanguageService implements vscode.Disposable {
  private client?: LanguageClient;
  private clientManifestPath?: string;
  private startPromise?: Promise<boolean>;
  private stateValue: QpmQmlLanguageServerState = 'stopped';
  private lastErrorValue?: string;
  private readonly output: vscode.OutputChannel;
  private readonly traceOutput: vscode.OutputChannel;
  private readonly emitter = new vscode.EventEmitter<void>();
  readonly onDidChange = this.emitter.event;

  constructor(
    private readonly workspaces: QpmWorkspaceService,
    private readonly qtInstallations: QpmQtInstallationService,
    private readonly sharedOutput: vscode.OutputChannel
  ) {
    this.output = vscode.window.createOutputChannel('QPM QML Language Server');
    this.traceOutput = vscode.window.createOutputChannel('QPM QML Language Server Trace');
  }

  get state(): QpmQmlLanguageServerState { return this.stateValue; }

  getReport(): QpmQmlLanguageReport | undefined {
    const context = this.resolveContext();
    if (!context) return undefined;
    const files = resolveQtProjectFiles(context.manifestPath, context.manifest);
    return {
      project: context.manifest.name,
      projectRoot: context.root,
      state: context.manifest.qml.languageServer.enabled ? this.stateValue : 'disabled',
      executable: context.executable,
      qtVersion: context.installation?.version,
      buildDirectories: context.buildDirectories,
      importPaths: context.importPaths,
      qmlFiles: files.qml.length,
      configurationFile: path.join(context.root, '.qmlls.ini'),
      officialExtensionInstalled: !!vscode.extensions.getExtension(OFFICIAL_QML_EXTENSION_ID),
      lastError: this.lastErrorValue
    };
  }

  async autoStartIfNeeded(): Promise<void> {
    const context = this.resolveContext();
    if (!context) {
      await this.stop(false);
      return;
    }
    const settings = context.manifest.qml.languageServer;
    if (!settings.enabled || !settings.autoStart || resolveQtProjectFiles(context.manifestPath, context.manifest).qml.length === 0) {
      await this.stop(false);
      this.setState(settings.enabled ? 'stopped' : 'disabled');
      return;
    }
    if (this.client && this.clientManifestPath === context.manifestPath && this.client.state === State.Running) {
      await this.publishBuildDirectories(context);
      return;
    }
    await this.start(false, false);
  }

  async start(force = false, notify = true): Promise<boolean> {
    if (this.startPromise) {
      const result = await this.startPromise;
      return !result && notify ? this.start(force, notify) : result;
    }
    const operation = this.startInternal(force, notify);
    this.startPromise = operation;
    try {
      return await operation;
    } finally {
      if (this.startPromise === operation) this.startPromise = undefined;
    }
  }

  private async startInternal(force = false, notify = true): Promise<boolean> {
    const context = this.resolveContext();
    if (!context) throw new Error('Open a native .qtproject.json project before starting QML Language Server.');
    const settings = context.manifest.qml.languageServer;
    if (!settings.enabled && !force) throw new Error('QML Language Server is disabled in Qt Project Settings.');
    if (!context.executable || !isFile(context.executable)) {
      this.lastErrorValue = 'qmlls was not found in the selected Qt kit or configured override.';
      this.setState('error');
      throw new Error(this.lastErrorValue);
    }

    const official = vscode.extensions.getExtension(OFFICIAL_QML_EXTENSION_ID);
    if (official && settings.conflictPolicy === 'avoid-duplicate' && !force) {
      this.lastErrorValue = `The official ${OFFICIAL_QML_EXTENSION_ID} extension is installed. QPM avoided starting a second qmlls instance.`;
      this.setState('conflict');
      if (notify) {
        const choice = await vscode.window.showWarningMessage(
          'Qt Project Manager did not start qmlls because the official Qt QML extension is installed. Running two language servers can duplicate diagnostics and completion items.',
          'Start QPM qmlls anyway', 'Open QML settings'
        );
        if (choice === 'Start QPM qmlls anyway') force = true;
        else {
          if (choice === 'Open QML settings') await vscode.commands.executeCommand('qpm.editBuildSettings');
          return false;
        }
      } else {
        return false;
      }
    }

    if (this.client) await this.stop(false);
    if (settings.generateConfigurationFile) await this.generateConfigurationFile(false, true);

    this.setState('starting');
    this.lastErrorValue = undefined;
    const args = createServerArguments(context);
    const env = createQmlEnvironment(context);
    const serverOptions: ServerOptions = {
      command: context.executable,
      args,
      options: { cwd: context.root, env, shell: false }
    };
    const selector: NonNullable<LanguageClientOptions['documentSelector']> = [
      { scheme: 'file', language: 'qml', pattern: '**/*.qml' },
      { scheme: 'file', pattern: '**/*.qml' }
    ];
    const clientOptions: LanguageClientOptions = {
      documentSelector: selector,
      workspaceFolder: context.workspaceFolder,
      outputChannel: this.output,
      traceOutputChannel: this.traceOutput,
      revealOutputChannelOn: settings.verboseOutput ? RevealOutputChannelOn.Info : RevealOutputChannelOn.Error,
      synchronize: {
        fileEvents: [
          vscode.workspace.createFileSystemWatcher(new vscode.RelativePattern(context.root, '**/*.{qml,qmldir,qmltypes,js,mjs,cpp,cxx,cc,h,hpp,hxx}')),
          vscode.workspace.createFileSystemWatcher(new vscode.RelativePattern(context.root, '**/{CMakeLists.txt,*.cmake,*.qtproject.json,.qmlls.ini}'))
        ]
      },
      initializationOptions: {
        qpm: {
          projectRoot: context.root,
          qtVersion: context.installation?.version,
          buildDirectories: context.buildDirectories,
          importPaths: context.importPaths
        }
      }
    };

    this.client = new LanguageClient('qpm-qmlls', `QPM QML Language Server — ${context.manifest.name}`, serverOptions, clientOptions);
    this.client.registerFeature(new QmllsDottedFileWatcherCompatibilityFeature(() => {
      this.log('Accepted qmlls compatibility registration for workspace.didChangeWatchedFiles; QPM file watchers remain active.');
    }));
    this.clientManifestPath = context.manifestPath;
    this.client.onDidChangeState((event) => {
      if (event.newState === State.Running) this.setState('running');
      else if (event.newState === State.Stopped && this.stateValue !== 'error') this.setState('stopped');
    });

    try {
      this.log(`Starting ${context.executable}`);
      this.log(`Arguments: ${args.map(quoteForLog).join(' ') || '(none)'}`);
      this.log(`Build directories: ${context.buildDirectories.join(path.delimiter) || '(none)'}`);
      this.log(`Import paths: ${context.importPaths.join(path.delimiter) || '(none)'}`);
      await this.client.start();
      await this.client.setTrace(traceValue(settings.trace));
      await this.publishBuildDirectories(context);
      this.setState('running');
      if (notify) vscode.window.showInformationMessage(`QML Language Server started for ${context.manifest.name}.`);
      return true;
    } catch (error) {
      this.lastErrorValue = error instanceof Error ? error.message : String(error);
      this.log(`Start failed: ${this.lastErrorValue}`);
      await this.stop(false);
      this.setState('error');
      if (notify) vscode.window.showErrorMessage(`QML Language Server failed to start: ${this.lastErrorValue}`);
      return false;
    }
  }

  async stop(notify = true): Promise<void> {
    const client = this.client;
    this.client = undefined;
    this.clientManifestPath = undefined;
    if (client) {
      try { await client.stop(5000); } catch { try { await client.dispose(); } catch { /* already stopped */ } }
    }
    this.setState('stopped');
    if (notify) vscode.window.showInformationMessage('QML Language Server stopped.');
  }

  async restart(): Promise<boolean> {
    await this.stop(false);
    return this.start(false, true);
  }

  async refreshBuildDirectories(): Promise<void> {
    const context = this.resolveContext();
    if (!context) return;
    if (this.client?.state === State.Running) await this.publishBuildDirectories(context);
    this.emitter.fire();
  }

  async generateConfigurationFile(notify = true, silentExisting = false): Promise<string | undefined> {
    const context = this.resolveContext();
    if (!context) throw new Error('Open a native Qt project before generating .qmlls.ini.');
    const target = path.join(context.root, '.qmlls.ini');
    if (fs.existsSync(target)) {
      const existing = fs.readFileSync(target, 'utf8');
      if (!existing.includes(GENERATED_MARKER)) {
        if (silentExisting) {
          this.log(`Keeping user-managed ${target}.`);
          return target;
        }
        const replace = await vscode.window.showWarningMessage('.qmlls.ini is not managed by QPM. Replace it?', { modal: true }, 'Replace');
        if (replace !== 'Replace') return undefined;
      }
    }
    const settings = context.manifest.qml.languageServer;
    const lines = [
      GENERATED_MARKER,
      '[General]',
      `no-cmake-calls=${settings.noCmakeCalls ? 'true' : 'false'}`,
      `CMakeJobs=${settings.cmakeJobs > 0 ? settings.cmakeJobs : 'max'}`,
      ...(context.buildDirectories[0] ? [`buildDir=${iniPath(context.buildDirectories[0])}`] : []),
      ...(context.importPaths.length ? [`importPaths=${context.importPaths.map(iniPath).join(path.delimiter)}`] : [])
    ];
    const content = `${lines.join('\n')}\n`;
    if (fs.existsSync(target) && fs.readFileSync(target, 'utf8') === content) return target;
    fs.writeFileSync(target, content, 'utf8');
    this.log(`Generated ${target}.`);
    if (notify) vscode.window.showInformationMessage(`Generated ${target}.`);
    this.emitter.fire();
    return target;
  }

  async openConfigurationFile(): Promise<void> {
    const context = this.resolveContext();
    if (!context) throw new Error('Open a native Qt project first.');
    const target = path.join(context.root, '.qmlls.ini');
    if (!fs.existsSync(target)) await this.generateConfigurationFile(false);
    if (fs.existsSync(target)) await vscode.window.showTextDocument(await vscode.workspace.openTextDocument(target), { preview: false });
  }

  async generateQmldir(): Promise<string | undefined> {
    const context = this.resolveContext();
    if (!context) throw new Error('Open a native Qt project before generating qmldir metadata.');
    const activeBuild = getActiveQtBuildProfile(context.manifest, getPersistedQtBuildMode(context.manifest));
    if (activeBuild.system === 'cmake') {
      const choice = await vscode.window.showWarningMessage(
        'CMake qt_add_qml_module normally generates qmldir metadata automatically. Generate a handwritten qmldir anyway?',
        { modal: true },
        'Generate qmldir'
      );
      if (choice !== 'Generate qmldir') return undefined;
    }
    const files = resolveQtProjectFiles(context.manifestPath, context.manifest).qml;
    const directories = uniquePaths(files.map((file) => path.dirname(file)).filter(isDirectory));
    let directory = directories[0] || path.resolve(context.root, context.manifest.qml.module.importRoot);
    if (directories.length > 1) {
      const picked = await vscode.window.showQuickPick(directories.map((entry) => ({ label: path.relative(context.root, entry) || '.', description: entry, value: entry })), { title: 'QML module directory' });
      if (!picked) return undefined;
      directory = picked.value;
    }
    fs.mkdirSync(directory, { recursive: true });
    const uri = await vscode.window.showInputBox({ title: 'QML module URI', value: context.manifest.qml.module.uri, validateInput: validateModuleUri });
    if (!uri) return undefined;
    const version = await vscode.window.showInputBox({ title: 'QML module version', value: context.manifest.qml.module.version, validateInput: validateModuleVersion });
    if (!version) return undefined;
    const qmlFiles = fs.readdirSync(directory, { withFileTypes: true })
      .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith('.qml'))
      .map((entry) => entry.name)
      .sort((a, b) => a.localeCompare(b));
    if (!qmlFiles.length) throw new Error(`No .qml files were found in ${directory}.`);
    const target = path.join(directory, 'qmldir');
    if (fs.existsSync(target)) {
      const replace = await vscode.window.showWarningMessage(`${target} already exists. Replace it?`, { modal: true }, 'Replace');
      if (replace !== 'Replace') return undefined;
    }
    const lines = [`module ${uri}`];
    for (const file of qmlFiles) {
      const typeName = path.basename(file, '.qml');
      if (!/^[A-Z][A-Za-z0-9_]*$/.test(typeName)) continue;
      const content = fs.readFileSync(path.join(directory, file), 'utf8');
      const prefix = /(^|\n)\s*pragma\s+Singleton\b/.test(content) ? 'singleton ' : '';
      lines.push(`${prefix}${typeName} ${version} ${file}`);
    }
    fs.writeFileSync(target, `${lines.join('\n')}\n`, 'utf8');
    context.manifest.qml.module.uri = uri;
    context.manifest.qml.module.version = version;
    const relativeRoot = path.relative(context.root, directory).replace(/\\/g, '/') || '.';
    context.manifest.qml.module.importRoot = relativeRoot;
    if (!context.manifest.qml.languageServer.importPaths.includes(relativeRoot)) context.manifest.qml.languageServer.importPaths.push(relativeRoot);
    writeQtProjectManifest(context.manifestPath, context.manifest);
    this.workspaces.refresh();
    this.log(`Generated ${target} with ${lines.length - 1} QML type entries.`);
    vscode.window.showInformationMessage(`Generated qmldir for ${uri} (${lines.length - 1} type entries).`);
    await this.restartIfRunning();
    return target;
  }

  async openReport(): Promise<void> {
    const report = this.getReport();
    if (!report) throw new Error('Open a native Qt project first.');
    const content = [
      `# QML Language Server — ${report.project}`,
      '',
      `- State: ${report.state}`,
      `- Executable: ${report.executable || 'not found'}`,
      `- Qt version: ${report.qtVersion || 'not resolved'}`,
      `- QML files: ${report.qmlFiles}`,
      `- Official Qt QML extension installed: ${report.officialExtensionInstalled ? 'yes' : 'no'}`,
      `- Configuration file: ${report.configurationFile}`,
      ...(report.lastError ? [`- Last error: ${report.lastError}`] : []),
      '',
      '## Build directories',
      '',
      ...(report.buildDirectories.length ? report.buildDirectories.map((entry) => `- ${entry}`) : ['- None']),
      '',
      '## Import paths',
      '',
      ...(report.importPaths.length ? report.importPaths.map((entry) => `- ${entry}`) : ['- None'])
    ].join('\n');
    await vscode.window.showTextDocument(await vscode.workspace.openTextDocument({ language: 'markdown', content }), { preview: true });
  }

  showOutput(): void { this.output.show(true); }
  showTraceOutput(): void { this.traceOutput.show(true); }

  dispose(): void {
    void this.stop(false);
    this.emitter.dispose();
    this.output.dispose();
    this.traceOutput.dispose();
  }

  private resolveContext(): ActiveQmlContext | undefined {
    const ref = this.workspaces.activeProjectRef;
    if (!ref?.exists || !isQtProjectManifestPath(ref.absolutePath)) return undefined;
    try {
      const manifest = readQtProjectManifest(ref.absolutePath);
      const root = path.dirname(ref.absolutePath);
      const mode = getPersistedQtBuildMode(manifest);
      const installation = this.qtInstallations.getActive(getQtInstallationPreference(manifest, mode));
      const executable = resolveExecutable(root, manifest.qml.languageServer.executable, installation?.qmlLanguageServerPath);
      const buildDirectories = resolveBuildDirectories(root, manifest);
      const importPaths = resolveImportPaths(ref.absolutePath, root, manifest, installation, buildDirectories);
      const workspaceFolder = vscode.workspace.getWorkspaceFolder(vscode.Uri.file(root));
      return { manifestPath: ref.absolutePath, root, manifest, installation, executable, buildDirectories, importPaths, workspaceFolder };
    } catch (error) {
      this.lastErrorValue = error instanceof Error ? error.message : String(error);
      return undefined;
    }
  }

  private async publishBuildDirectories(context: ActiveQmlContext): Promise<void> {
    if (!this.client || this.client.state !== State.Running || !context.workspaceFolder) return;
    await this.client.sendNotification('$/addBuildDirs', {
      buildDirsToSet: [{
        baseUri: context.workspaceFolder.uri.toString(),
        buildDirs: context.buildDirectories
      }]
    });
    this.log(`Published ${context.buildDirectories.length} build director${context.buildDirectories.length === 1 ? 'y' : 'ies'} through $/addBuildDirs.`);
  }

  private async restartIfRunning(): Promise<void> {
    if (this.client?.state === State.Running) await this.restart();
    else this.emitter.fire();
  }

  private setState(state: QpmQmlLanguageServerState): void {
    if (this.stateValue === state) return;
    this.stateValue = state;
    void vscode.commands.executeCommand('setContext', 'qpm.qmlLanguageServerState', state);
    this.emitter.fire();
  }

  private log(message: string): void {
    this.output.appendLine(`[QPM QML] ${message}`);
    this.sharedOutput.appendLine(`[QPM QML] ${message}`);
  }
}

class QmllsDottedFileWatcherCompatibilityFeature implements DynamicFeature<DidChangeWatchedFilesRegistrationOptions> {
  private readonly registrations = new Set<string>();
  readonly registrationType = new RegistrationType<DidChangeWatchedFilesRegistrationOptions>('workspace.didChangeWatchedFiles');

  constructor(private readonly onRegister: () => void) {}

  fillClientCapabilities(capabilities: ClientCapabilities): void {
    capabilities.workspace ??= {};
    capabilities.workspace.didChangeWatchedFiles ??= {};
    capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = true;
    capabilities.workspace.didChangeWatchedFiles.relativePatternSupport = true;
  }

  initialize(_capabilities: ServerCapabilities, _documentSelector: DocumentSelector | undefined): void {}

  getState(): FeatureState {
    return { kind: 'workspace', id: this.registrationType.method, registrations: this.registrations.size > 0 };
  }

  register(data: RegistrationData<DidChangeWatchedFilesRegistrationOptions>): void {
    this.registrations.add(data.id);
    this.onRegister();
  }

  unregister(id: string): void { this.registrations.delete(id); }
  clear(): void { this.registrations.clear(); }
}

function createServerArguments(context: ActiveQmlContext): string[] {
  const settings = context.manifest.qml.languageServer;
  const args: string[] = [];
  if (context.buildDirectories[0]) args.push('--build-dir', context.buildDirectories[0]);
  if (settings.noCmakeCalls) args.push('--no-cmake-calls');
  if (settings.cmakeJobs > 0) args.push('--cmake-jobs', String(settings.cmakeJobs));
  for (const importPath of context.importPaths) args.push('-I', importPath);
  if (settings.useQmlImportPathEnvironment) args.push('-E');
  if (settings.verboseOutput) args.push('--verbose');
  args.push(...settings.additionalArguments);
  return args;
}

function createQmlEnvironment(context: ActiveQmlContext): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = { ...process.env };
  const pathKey = Object.keys(env).find((entry) => entry.toLowerCase() === 'path') || 'PATH';
  const executableDirectory = context.executable ? path.dirname(context.executable) : undefined;
  const toolchainDirectory = context.installation?.toolchain.binDir;
  env[pathKey] = uniquePaths([context.installation?.binDir, executableDirectory, toolchainDirectory, env[pathKey]].filter((entry): entry is string => !!entry)).join(path.delimiter);
  if (context.installation?.root) env.QTDIR = context.installation.root;
  if (context.installation?.pluginsDir) env.QT_PLUGIN_PATH = context.installation.pluginsDir;
  if (context.importPaths.length) {
    env.QML_IMPORT_PATH = context.importPaths.join(path.delimiter);
    env.QML2_IMPORT_PATH = context.importPaths.join(path.delimiter);
  }
  env.QMLLS_BUILD_DIRS = context.buildDirectories.join(path.delimiter);
  if (context.manifest.qml.languageServer.noCmakeCalls) env.QMLLS_NO_CMAKE_CALLS = '1';
  if (context.manifest.qml.languageServer.cmakeJobs > 0) env.QMLLS_CMAKE_JOBS = String(context.manifest.qml.languageServer.cmakeJobs);
  env.QMLLS_MAX_FILES_TO_SEARCH = String(context.manifest.qml.languageServer.maxFilesToSearch);
  return env;
}

function resolveBuildDirectories(root: string, manifest: QtProjectManifest): string[] {
  const mode = getPersistedQtBuildMode(manifest);
  const profile = getActiveQtBuildProfile(manifest, mode);
  const modeFolder = mode === 'release' || mode === 'release64' ? 'release' : 'debug';
  const automatic = profile.system === 'direct'
    ? path.resolve(root, profile.outputDirectory, modeFolder)
    : path.resolve(root, profile.outputDirectory, modeFolder, profile.system);
  return uniquePaths([automatic, ...manifest.qml.languageServer.buildDirectories.map((entry) => resolveProjectPath(root, entry))]);
}

function resolveImportPaths(manifestPath: string, root: string, manifest: QtProjectManifest, installation: QpmQtInstallation | undefined, buildDirectories: string[]): string[] {
  const files = resolveQtProjectFiles(manifestPath, manifest);
  const qmlDirectories = files.qml.map((entry) => path.dirname(entry));
  return uniquePaths([
    installation?.qmlDir,
    path.resolve(root, manifest.qml.module.importRoot),
    ...qmlDirectories,
    ...manifest.qml.languageServer.importPaths.map((entry) => resolveProjectPath(root, entry)),
    ...buildDirectories
  ].filter((entry): entry is string => !!entry));
}

function resolveExecutable(root: string, configured: string, detected?: string): string | undefined {
  const candidates = [configured ? resolveProjectPath(root, configured) : undefined, detected].filter((entry): entry is string => !!entry);
  return candidates.find(isFile);
}

function resolveProjectPath(root: string, value: string): string {
  return path.isAbsolute(value) ? path.normalize(value) : path.resolve(root, value);
}

function uniquePaths(values: string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const value of values) {
    const normalized = path.normalize(value);
    const key = process.platform === 'win32' ? normalized.toLowerCase() : normalized;
    if (!seen.has(key)) { seen.add(key); result.push(normalized); }
  }
  return result;
}

function isFile(value: string | undefined): value is string {
  if (!value) return false;
  try { return fs.statSync(value).isFile(); } catch { return false; }
}

function isDirectory(value: string): boolean {
  try { return fs.statSync(value).isDirectory(); } catch { return false; }
}

function traceValue(value: QtProjectManifest['qml']['languageServer']['trace']): Trace {
  return value === 'verbose' ? Trace.Verbose : value === 'messages' ? Trace.Messages : Trace.Off;
}

function iniPath(value: string): string { return value.replace(/\\/g, '/'); }
function quoteForLog(value: string): string { return /\s/.test(value) ? `"${value.replace(/"/g, '\\"')}"` : value; }
function validateModuleUri(value: string): string | undefined { return /^[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*$/.test(value.trim()) ? undefined : 'Use a dotted QML URI such as Company.Controls.'; }
function validateModuleVersion(value: string): string | undefined { return /^\d+\.\d+$/.test(value.trim()) ? undefined : 'Use a major.minor version such as 1.0.'; }
