import * as vscode from 'vscode';
import { getActiveQtBuildProfile, getQtKitProfileForBuild, isQtProjectManifestPath, readQtProjectManifest } from '../model/qtProjectManifest';
import { QpmQtKitRegistryService } from '../services/qpmQtKitRegistryService';
import { QpmWorkspaceService } from '../services/qpmWorkspaceService';

export class QpmQtKitsProvider implements vscode.TreeDataProvider<QtKitTreeItem>, vscode.Disposable {
  private readonly changed = new vscode.EventEmitter<QtKitTreeItem | undefined>();
  readonly onDidChangeTreeData = this.changed.event;
  private view?: vscode.TreeView<QtKitTreeItem>;

  constructor(private readonly workspaces: QpmWorkspaceService, private readonly registry: QpmQtKitRegistryService) {}

  attachView(view: vscode.TreeView<QtKitTreeItem>): void { this.view = view; }
  refresh(): void { this.changed.fire(undefined); }
  dispose(): void { this.changed.dispose(); }
  getTreeItem(element: QtKitTreeItem): vscode.TreeItem { return element; }

  getChildren(element?: QtKitTreeItem): QtKitTreeItem[] {
    if (element?.children) return element.children;
    if (element) return [];
    const result: QtKitTreeItem[] = [];
    const ref = this.workspaces.activeProjectRef;
    if (ref?.exists && isQtProjectManifestPath(ref.absolutePath)) {
      try {
        const manifest = readQtProjectManifest(ref.absolutePath);
        const mode = vscode.workspace.getConfiguration('qpm').get<any>('buildMode', 'debug64');
        const build = getActiveQtBuildProfile(manifest, mode);
        const kit = getQtKitProfileForBuild(manifest, mode);
        result.push(item('Active backend', `${build.system} · ${build.name}`, 'server-process', 'qpm.showQtBuildPlan'));
        result.push(item('Project kit', kit.name, 'tools', 'qpm.manageQtProfiles'));
        result.push(item('Parallel jobs', build.parallelJobs > 0 ? String(build.parallelJobs) : 'Automatic', 'run-all'));
        result.push(item(
          'Backend files',
          build.system === 'direct' ? 'Native manifest and generated Qt files' : build.generateProjectFiles ? 'Generated by QPM' : (build.projectFile || build.sourceDirectory),
          'file-code',
          build.system === 'direct' ? 'qpm.showQtBuildPlan' : 'qpm.openQtBackendProject'
        ));
      } catch { /* project health reports details */ }
    } else {
      result.push(item('No native Qt project', 'Open a .qtproject.json project', 'info'));
    }
    const kits = this.registry.list();
    result.push(new QtKitTreeItem('Named kits', `${kits.length}`, vscode.TreeItemCollapsibleState.Expanded, undefined, undefined, kits.map((kit) => item(kit.name, `${kit.qtVersion} · ${kit.compilerFamily ?? 'unknown'} ${kit.architecture}`, 'tools'))));
    result.push(item('Select build backend…', 'Direct, qmake or CMake', 'server-process', 'qpm.selectQtBackend'));
    result.push(item('Import .pro or CMakeLists.txt…', 'Use an existing Qt build project', 'folder-opened', 'qpm.importQtBuildProject'));
    result.push(item('Manage named kits…', 'Detect, add, rename or delete', 'settings-gear', 'qpm.manageQtKits'));
    result.push(item('Assign kit to active project…', 'Use a reusable named kit', 'link', 'qpm.assignQtKit'));
    result.push(item('Configure active backend', 'Run qmake or CMake configure', 'gear', 'qpm.configureQtBackend'));
    result.push(item('Open generated backend project', 'Open .pro or CMakeLists.txt', 'file-code', 'qpm.openQtBackendProject'));
    return result;
  }
}

export class QtKitTreeItem extends vscode.TreeItem {
  constructor(
    label: string,
    description: string,
    collapsibleState: vscode.TreeItemCollapsibleState,
    command?: vscode.Command,
    icon?: vscode.ThemeIcon,
    readonly children?: QtKitTreeItem[]
  ) {
    super(label, collapsibleState);
    this.description = description;
    this.command = command;
    this.iconPath = icon;
    this.contextValue = 'qpmQtKitItem';
  }
}

function item(label: string, description: string, iconName: string, commandId?: string): QtKitTreeItem {
  return new QtKitTreeItem(label, description, vscode.TreeItemCollapsibleState.None, commandId ? { command: commandId, title: label } : undefined, new vscode.ThemeIcon(iconName));
}
